name: PR_MERGED
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy:
    if: github.event.pull_request.merged_by != ''
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - uses: julia-actions/setup-julia@0b9b1d2cd24245f151902702d8e73b3f6b910014 # v1.6.0
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install dependencies by running Pkg.instantiate()
        run: julia --project=.ci/ .ci/startup.jl
      - name: PR.run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_TOKEN: ${{ secrets.DCB_GITHUB_TOKEN }}
        run: julia --project=.ci/ .ci/pr_merged.jl
        shell: bash